name: baharudin_alarm
description: An alarm app made with Flutter for Stockbit and Bibit test assignment
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^9.8.0+1
  dynamic_color: ^1.2.3
  equatable: ^2.0.5
  timezone: ^0.8.0
  device_info_plus: ^4.1.2
  shared_preferences: ^2.0.15
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true